<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<!-- <p>Social Links</p> -->
<div class="vs-social-icons">
    <a href="#" class="footer__social-links">
        <i class="fa-brands fa-instagram"></i>
    </a>

    <a href="#" class="footer__social-links">
        <i class="fa-brands fa-youtube"></i>
    </a>

    <a href="#" class="footer__social-links">
        <i class="fa-brands fa-square-facebook"></i>
    </a>

    <a href="#" class="footer__social-links">
        <i class="fa-brands fa-twitter"></i>
    </a>

    <a href="#" class="footer__social-links">
        <i class="fa-brands fa-whatsapp"></i>
    </a>
</div>

<p class="vs-footer-copyright__paragraph">Copyright 2022 Digital Plus. All Rights Reserved</p>