<?php
?>

<div class="store-features__main-container">


    <div class="vs-feature_container vs__flex-row">
        <!-- <i class="fa-regular fa-mobile-notch"></i> -->
        <!-- <i class="fa-brands fa-square-facebook"></i> -->
        <i class="fa-solid fa-mobile-screen-button"></i>
        <div class="vs-feature__feature-text vs__flex-column">
            <h3 class="vs-features__heading">Store at Home</h3>
            <p class="vs-features-detail__paragraph">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
        </div>
    </div>

    <div class="vs-feature_container vs__flex-row">
        <!-- <i class="fa-regular fa-truck-container"></i> -->
        <!-- <i class="fa-brands fa-square-facebook"></i> -->
        <i class="fa-solid fa-truck-front"></i>
        <div class="vs-feature__feature-text vs__flex-column">
            <h3 class="vs-features__heading">Free Delivery</h3>
            <p class="vs-features-detail__paragraph">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
        </div>
    </div>

    <div class="vs-feature_container vs__flex-row">
        <!-- <i class="fa-regular fa-send-back"></i> -->
        <!-- <i class="fa-brands fa-square-facebook"></i> -->
        <i class="fa-solid fa-rotate-left"></i>
        <div class="vs-feature__feature-text vs__flex-column">
            <h3 class="vs-features__heading">Easy Returns</h3>
            <p class="vs-features-detail__paragraph">Lorem ipsum dolor sit amet consectetur, adipisicing elit.</p>
        </div>
    </div>



</div>