<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<h3 class="vs-footer_heading">Useful Links</h3>

<ul class="vs-footer__useful-links">
    <li class="vs-footer__list-item__useful-links"><a href="#" class="vs-useful-links__links">Help &amp; Support</a></li>
    <li class="vs-footer__list-item__useful-links"><a href="http://digiplus.magento.com/privacy-policy-cookie-restriction-mode/" class="vs-useful-links__links">Privacy Policy</a></li>
    <li class="vs-footer__list-item__useful-links"><a href="#" class="vs-useful-links__links">Return Policy</a></li>
    <li class="vs-footer__list-item__useful-links"><a href="#" class="vs-useful-links__links">Terms of Use</a></li>
    <li class="vs-footer__list-item__useful-links"><a href="#" class="vs-useful-links__links">Disclaimer</a></li>
    <li class="vs-footer__list-item__useful-links"><a href="#" class="vs-useful-links__links">FAQ's</a></li>
</ul>